name: tsi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _pytorch_select
  - asn1crypto
  - attrs
  - backcall
  - blas
  - bleach
  - blosc
  - bzip2
  - ca-certificates
  - captum
  - certifi
  - cffi
  - chardet
  - cryptography
#  - cuda90
  - cudatoolkit
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fontconfig
  - freetype
  - glib
  - gmp
  - gst-plugins-base
  - gstreamer
  - hdf5
  - icu
  - idna
  - imbalanced-learn
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - krb5
#  - ld_impl_linux-64
  - libedit
  - libffi
#  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libpq
  - libsodium
#  - libstdcxx-ng
  - libtiff
  - libuuid
#  - libxcb
  - libxml2
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - ninja
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt_toolkit
  - psycopg2
  - ptyprocess
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytables
  - python
  - python-dateutil
  - pytorch
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - readline
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - snappy
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - tk
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xgboost
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - h5py
    - imageio
    - jitcdde
    - jitcxde-common
    - lime
    - mock
    - mpmath
    - networkx
    - numexpr
    - pydlm
    - pywavelets
    - scikit-image
    - shap
    - symengine
    - sympy
    - tables
    - timesynth
